image: openjdk:8-jdk

variables:
  CACHE_DIR: "$CI_PROJECT_DIR/build"
  CACHE_DIR2: "$CI_PROJECT_DIR/.gradle"

  ORIG_ARTIFACTS: "$CI_PROJECT_DIR/build/libs/*.jar"
  ARTIFACTS: "$CI_PROJECT_DIR/*.jar"

cache:
  paths:
    - $CACHE_DIR
    - $CACHE_DIR2
  key: "$CI_BUILD_REF_NAME"
  untracked: false

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - ./gradlew clean
    - cp $ORIG_ARTIFACTS .
  artifacts:
    paths:
      - $ARTIFACTS
